// Pokemon types based on Pokedex numbers
// This is a simplified version with common types for first few generations
// In a real application, this would be a comprehensive database

export interface PokemonType {
  dexNumber: number;
  name: string;
  types: string[];
}

export const pokemonTypes: PokemonType[] = [
  // Gen 1 (1-151)
  { dexNumber: 1, name: "Bulbasaur", types: ["Grass", "Poison"] },
  { dexNumber: 2, name: "Ivysaur", types: ["Grass", "Poison"] },
  { dexNumber: 3, name: "Venusaur", types: ["Grass", "Poison"] },
  { dexNumber: 4, name: "Charmander", types: ["Fire"] },
  { dexNumber: 5, name: "Charmeleon", types: ["Fire"] },
  { dexNumber: 6, name: "Charizard", types: ["Fire", "Flying"] },
  { dexNumber: 7, name: "Squirtle", types: ["Water"] },
  { dexNumber: 8, name: "Wartortle", types: ["Water"] },
  { dexNumber: 9, name: "Blastoise", types: ["Water"] },
  { dexNumber: 10, name: "Caterpie", types: ["Bug"] },
  { dexNumber: 11, name: "Metapod", types: ["Bug"] },
  { dexNumber: 12, name: "Butterfree", types: ["Bug", "Flying"] },
  { dexNumber: 13, name: "Weedle", types: ["Bug", "Poison"] },
  { dexNumber: 14, name: "Kakuna", types: ["Bug", "Poison"] },
  { dexNumber: 15, name: "Beedrill", types: ["Bug", "Poison"] },
  { dexNumber: 16, name: "Pidgey", types: ["Normal", "Flying"] },
  { dexNumber: 17, name: "Pidgeotto", types: ["Normal", "Flying"] },
  { dexNumber: 18, name: "Pidgeot", types: ["Normal", "Flying"] },
  { dexNumber: 19, name: "Rattata", types: ["Normal"] },
  { dexNumber: 20, name: "Raticate", types: ["Normal"] },
  { dexNumber: 21, name: "Spearow", types: ["Normal", "Flying"] },
  { dexNumber: 22, name: "Fearow", types: ["Normal", "Flying"] },
  { dexNumber: 23, name: "Ekans", types: ["Poison"] },
  { dexNumber: 24, name: "Arbok", types: ["Poison"] },
  { dexNumber: 25, name: "Pikachu", types: ["Electric"] },
  { dexNumber: 26, name: "Raichu", types: ["Electric"] },
  { dexNumber: 27, name: "Sandshrew", types: ["Ground"] },
  { dexNumber: 28, name: "Sandslash", types: ["Ground"] },
  { dexNumber: 29, name: "Nidoran♀", types: ["Poison"] },
  { dexNumber: 30, name: "Nidorina", types: ["Poison"] },
  { dexNumber: 31, name: "Nidoqueen", types: ["Poison", "Ground"] },
  { dexNumber: 32, name: "Nidoran♂", types: ["Poison"] },
  { dexNumber: 33, name: "Nidorino", types: ["Poison"] },
  { dexNumber: 34, name: "Nidoking", types: ["Poison", "Ground"] },
  { dexNumber: 35, name: "Clefairy", types: ["Fairy"] },
  { dexNumber: 36, name: "Clefable", types: ["Fairy"] },
  { dexNumber: 37, name: "Vulpix", types: ["Fire"] },
  { dexNumber: 38, name: "Ninetales", types: ["Fire"] },
  { dexNumber: 39, name: "Jigglypuff", types: ["Normal", "Fairy"] },
  { dexNumber: 40, name: "Wigglytuff", types: ["Normal", "Fairy"] },
  { dexNumber: 41, name: "Zubat", types: ["Poison", "Flying"] },
  { dexNumber: 42, name: "Golbat", types: ["Poison", "Flying"] },
  { dexNumber: 43, name: "Oddish", types: ["Grass", "Poison"] },
  { dexNumber: 44, name: "Gloom", types: ["Grass", "Poison"] },
  { dexNumber: 45, name: "Vileplume", types: ["Grass", "Poison"] },
  { dexNumber: 46, name: "Paras", types: ["Bug", "Grass"] },
  { dexNumber: 47, name: "Parasect", types: ["Bug", "Grass"] },
  { dexNumber: 48, name: "Venonat", types: ["Bug", "Poison"] },
  { dexNumber: 49, name: "Venomoth", types: ["Bug", "Poison"] },
  { dexNumber: 50, name: "Diglett", types: ["Ground"] },
  { dexNumber: 51, name: "Dugtrio", types: ["Ground"] },
  { dexNumber: 52, name: "Meowth", types: ["Normal"] },
  { dexNumber: 53, name: "Persian", types: ["Normal"] },
  { dexNumber: 54, name: "Psyduck", types: ["Water"] },
  { dexNumber: 55, name: "Golduck", types: ["Water"] },
  { dexNumber: 56, name: "Mankey", types: ["Fighting"] },
  { dexNumber: 57, name: "Primeape", types: ["Fighting"] },
  { dexNumber: 58, name: "Growlithe", types: ["Fire"] },
  { dexNumber: 59, name: "Arcanine", types: ["Fire"] },
  { dexNumber: 60, name: "Poliwag", types: ["Water"] },
  { dexNumber: 61, name: "Poliwhirl", types: ["Water"] },
  { dexNumber: 62, name: "Poliwrath", types: ["Water", "Fighting"] },
  { dexNumber: 63, name: "Abra", types: ["Psychic"] },
  { dexNumber: 64, name: "Kadabra", types: ["Psychic"] },
  { dexNumber: 65, name: "Alakazam", types: ["Psychic"] },
  { dexNumber: 66, name: "Machop", types: ["Fighting"] },
  { dexNumber: 67, name: "Machoke", types: ["Fighting"] },
  { dexNumber: 68, name: "Machamp", types: ["Fighting"] },
  { dexNumber: 69, name: "Bellsprout", types: ["Grass", "Poison"] },
  { dexNumber: 70, name: "Weepinbell", types: ["Grass", "Poison"] },
  { dexNumber: 71, name: "Victreebel", types: ["Grass", "Poison"] },
  { dexNumber: 72, name: "Tentacool", types: ["Water", "Poison"] },
  { dexNumber: 73, name: "Tentacruel", types: ["Water", "Poison"] },
  { dexNumber: 74, name: "Geodude", types: ["Rock", "Ground"] },
  { dexNumber: 75, name: "Graveler", types: ["Rock", "Ground"] },
  { dexNumber: 76, name: "Golem", types: ["Rock", "Ground"] },
  { dexNumber: 77, name: "Ponyta", types: ["Fire"] },
  { dexNumber: 78, name: "Rapidash", types: ["Fire"] },
  { dexNumber: 79, name: "Slowpoke", types: ["Water", "Psychic"] },
  { dexNumber: 80, name: "Slowbro", types: ["Water", "Psychic"] },
  { dexNumber: 81, name: "Magnemite", types: ["Electric", "Steel"] },
  { dexNumber: 82, name: "Magneton", types: ["Electric", "Steel"] },
  { dexNumber: 83, name: "Farfetch'd", types: ["Normal", "Flying"] },
  { dexNumber: 84, name: "Doduo", types: ["Normal", "Flying"] },
  { dexNumber: 85, name: "Dodrio", types: ["Normal", "Flying"] },
  { dexNumber: 86, name: "Seel", types: ["Water"] },
  { dexNumber: 87, name: "Dewgong", types: ["Water", "Ice"] },
  { dexNumber: 88, name: "Grimer", types: ["Poison"] },
  { dexNumber: 89, name: "Muk", types: ["Poison"] },
  { dexNumber: 90, name: "Shellder", types: ["Water"] },
  { dexNumber: 91, name: "Cloyster", types: ["Water", "Ice"] },
  { dexNumber: 92, name: "Gastly", types: ["Ghost", "Poison"] },
  { dexNumber: 93, name: "Haunter", types: ["Ghost", "Poison"] },
  { dexNumber: 94, name: "Gengar", types: ["Ghost", "Poison"] },
  { dexNumber: 95, name: "Onix", types: ["Rock", "Ground"] },
  { dexNumber: 96, name: "Drowzee", types: ["Psychic"] },
  { dexNumber: 97, name: "Hypno", types: ["Psychic"] },
  { dexNumber: 98, name: "Krabby", types: ["Water"] },
  { dexNumber: 99, name: "Kingler", types: ["Water"] },
  { dexNumber: 100, name: "Voltorb", types: ["Electric"] },
  { dexNumber: 101, name: "Electrode", types: ["Electric"] },
  { dexNumber: 102, name: "Exeggcute", types: ["Grass", "Psychic"] },
  { dexNumber: 103, name: "Exeggutor", types: ["Grass", "Psychic"] },
  { dexNumber: 104, name: "Cubone", types: ["Ground"] },
  { dexNumber: 105, name: "Marowak", types: ["Ground"] },
  { dexNumber: 106, name: "Hitmonlee", types: ["Fighting"] },
  { dexNumber: 107, name: "Hitmonchan", types: ["Fighting"] },
  { dexNumber: 108, name: "Lickitung", types: ["Normal"] },
  { dexNumber: 109, name: "Koffing", types: ["Poison"] },
  { dexNumber: 110, name: "Weezing", types: ["Poison"] },
  { dexNumber: 111, name: "Rhyhorn", types: ["Ground", "Rock"] },
  { dexNumber: 112, name: "Rhydon", types: ["Ground", "Rock"] },
  { dexNumber: 113, name: "Chansey", types: ["Normal"] },
  { dexNumber: 114, name: "Tangela", types: ["Grass"] },
  { dexNumber: 115, name: "Kangaskhan", types: ["Normal"] },
  { dexNumber: 116, name: "Horsea", types: ["Water"] },
  { dexNumber: 117, name: "Seadra", types: ["Water"] },
  { dexNumber: 118, name: "Goldeen", types: ["Water"] },
  { dexNumber: 119, name: "Seaking", types: ["Water"] },
  { dexNumber: 120, name: "Staryu", types: ["Water"] },
  { dexNumber: 121, name: "Starmie", types: ["Water", "Psychic"] },
  { dexNumber: 122, name: "Mr. Mime", types: ["Psychic", "Fairy"] },
  { dexNumber: 123, name: "Scyther", types: ["Bug", "Flying"] },
  { dexNumber: 124, name: "Jynx", types: ["Ice", "Psychic"] },
  { dexNumber: 125, name: "Electabuzz", types: ["Electric"] },
  { dexNumber: 126, name: "Magmar", types: ["Fire"] },
  { dexNumber: 127, name: "Pinsir", types: ["Bug"] },
  { dexNumber: 128, name: "Tauros", types: ["Normal"] },
  { dexNumber: 129, name: "Magikarp", types: ["Water"] },
  { dexNumber: 130, name: "Gyarados", types: ["Water", "Flying"] },
  { dexNumber: 131, name: "Lapras", types: ["Water", "Ice"] },
  { dexNumber: 132, name: "Ditto", types: ["Normal"] },
  { dexNumber: 133, name: "Eevee", types: ["Normal"] },
  { dexNumber: 134, name: "Vaporeon", types: ["Water"] },
  { dexNumber: 135, name: "Jolteon", types: ["Electric"] },
  { dexNumber: 136, name: "Flareon", types: ["Fire"] },
  { dexNumber: 137, name: "Porygon", types: ["Normal"] },
  { dexNumber: 138, name: "Omanyte", types: ["Rock", "Water"] },
  { dexNumber: 139, name: "Omastar", types: ["Rock", "Water"] },
  { dexNumber: 140, name: "Kabuto", types: ["Rock", "Water"] },
  { dexNumber: 141, name: "Kabutops", types: ["Rock", "Water"] },
  { dexNumber: 142, name: "Aerodactyl", types: ["Rock", "Flying"] },
  { dexNumber: 143, name: "Snorlax", types: ["Normal"] },
  { dexNumber: 144, name: "Articuno", types: ["Ice", "Flying"] },
  { dexNumber: 145, name: "Zapdos", types: ["Electric", "Flying"] },
  { dexNumber: 146, name: "Moltres", types: ["Fire", "Flying"] },
  { dexNumber: 147, name: "Dratini", types: ["Dragon"] },
  { dexNumber: 148, name: "Dragonair", types: ["Dragon"] },
  { dexNumber: 149, name: "Dragonite", types: ["Dragon", "Flying"] },
  { dexNumber: 150, name: "Mewtwo", types: ["Psychic"] },
  { dexNumber: 151, name: "Mew", types: ["Psychic"] },

  // Gen 2 (152-251)
  { dexNumber: 152, name: "Chikorita", types: ["Grass"] },
  { dexNumber: 153, name: "Bayleef", types: ["Grass"] },
  { dexNumber: 154, name: "Meganium", types: ["Grass"] },
  { dexNumber: 155, name: "Cyndaquil", types: ["Fire"] },
  { dexNumber: 156, name: "Quilava", types: ["Fire"] },
  { dexNumber: 157, name: "Typhlosion", types: ["Fire"] },
  { dexNumber: 158, name: "Totodile", types: ["Water"] },
  { dexNumber: 159, name: "Croconaw", types: ["Water"] },
  { dexNumber: 160, name: "Feraligatr", types: ["Water"] },
  { dexNumber: 161, name: "Sentret", types: ["Normal"] },
  { dexNumber: 162, name: "Furret", types: ["Normal"] },
  { dexNumber: 163, name: "Hoothoot", types: ["Normal", "Flying"] },
  { dexNumber: 164, name: "Noctowl", types: ["Normal", "Flying"] },
  { dexNumber: 165, name: "Ledyba", types: ["Bug", "Flying"] },
  { dexNumber: 166, name: "Ledian", types: ["Bug", "Flying"] },
  { dexNumber: 167, name: "Spinarak", types: ["Bug", "Poison"] },
  { dexNumber: 168, name: "Ariados", types: ["Bug", "Poison"] },
  { dexNumber: 169, name: "Crobat", types: ["Poison", "Flying"] },
  { dexNumber: 170, name: "Chinchou", types: ["Water", "Electric"] },
  { dexNumber: 171, name: "Lanturn", types: ["Water", "Electric"] },
  { dexNumber: 172, name: "Pichu", types: ["Electric"] },
  { dexNumber: 173, name: "Cleffa", types: ["Fairy"] },
  { dexNumber: 174, name: "Igglybuff", types: ["Normal", "Fairy"] },
  { dexNumber: 175, name: "Togepi", types: ["Fairy"] },
  { dexNumber: 176, name: "Togetic", types: ["Fairy", "Flying"] },
  { dexNumber: 177, name: "Natu", types: ["Psychic", "Flying"] },
  { dexNumber: 178, name: "Xatu", types: ["Psychic", "Flying"] },
  { dexNumber: 179, name: "Mareep", types: ["Electric"] },
  { dexNumber: 180, name: "Flaaffy", types: ["Electric"] },
  { dexNumber: 181, name: "Ampharos", types: ["Electric"] },
  { dexNumber: 182, name: "Bellossom", types: ["Grass"] },
  { dexNumber: 183, name: "Marill", types: ["Water", "Fairy"] },
  { dexNumber: 184, name: "Azumarill", types: ["Water", "Fairy"] },
  { dexNumber: 185, name: "Sudowoodo", types: ["Rock"] },
  { dexNumber: 186, name: "Politoed", types: ["Water"] },
  { dexNumber: 187, name: "Hoppip", types: ["Grass", "Flying"] },
  { dexNumber: 188, name: "Skiploom", types: ["Grass", "Flying"] },
  { dexNumber: 189, name: "Jumpluff", types: ["Grass", "Flying"] },
  { dexNumber: 190, name: "Aipom", types: ["Normal"] },
  { dexNumber: 191, name: "Sunkern", types: ["Grass"] },
  { dexNumber: 192, name: "Sunflora", types: ["Grass"] },
  { dexNumber: 193, name: "Yanma", types: ["Bug", "Flying"] },
  { dexNumber: 194, name: "Wooper", types: ["Water", "Ground"] },
  { dexNumber: 195, name: "Quagsire", types: ["Water", "Ground"] },
  { dexNumber: 196, name: "Espeon", types: ["Psychic"] },
  { dexNumber: 197, name: "Umbreon", types: ["Dark"] },
  { dexNumber: 198, name: "Murkrow", types: ["Dark", "Flying"] },
  { dexNumber: 199, name: "Slowking", types: ["Water", "Psychic"] },
  { dexNumber: 200, name: "Misdreavus", types: ["Ghost"] },
  { dexNumber: 201, name: "Unown", types: ["Psychic"] },
  { dexNumber: 202, name: "Wobbuffet", types: ["Psychic"] },
  { dexNumber: 203, name: "Girafarig", types: ["Normal", "Psychic"] },
  { dexNumber: 204, name: "Pineco", types: ["Bug"] },
  { dexNumber: 205, name: "Forretress", types: ["Bug", "Steel"] },
  { dexNumber: 206, name: "Dunsparce", types: ["Normal"] },
  { dexNumber: 207, name: "Gligar", types: ["Ground", "Flying"] },
  { dexNumber: 208, name: "Steelix", types: ["Steel", "Ground"] },
  { dexNumber: 209, name: "Snubbull", types: ["Fairy"] },
  { dexNumber: 210, name: "Granbull", types: ["Fairy"] },
  { dexNumber: 211, name: "Qwilfish", types: ["Water", "Poison"] },
  { dexNumber: 212, name: "Scizor", types: ["Bug", "Steel"] },
  { dexNumber: 213, name: "Shuckle", types: ["Bug", "Rock"] },
  { dexNumber: 214, name: "Heracross", types: ["Bug", "Fighting"] },
  { dexNumber: 215, name: "Sneasel", types: ["Dark", "Ice"] },
  { dexNumber: 216, name: "Teddiursa", types: ["Normal"] },
  { dexNumber: 217, name: "Ursaring", types: ["Normal"] },
  { dexNumber: 218, name: "Slugma", types: ["Fire"] },
  { dexNumber: 219, name: "Magcargo", types: ["Fire", "Rock"] },
  { dexNumber: 220, name: "Swinub", types: ["Ice", "Ground"] },
  { dexNumber: 221, name: "Piloswine", types: ["Ice", "Ground"] },
  { dexNumber: 222, name: "Corsola", types: ["Water", "Rock"] },
  { dexNumber: 223, name: "Remoraid", types: ["Water"] },
  { dexNumber: 224, name: "Octillery", types: ["Water"] },
  { dexNumber: 225, name: "Delibird", types: ["Ice", "Flying"] },
  { dexNumber: 226, name: "Mantine", types: ["Water", "Flying"] },
  { dexNumber: 227, name: "Skarmory", types: ["Steel", "Flying"] },
  { dexNumber: 228, name: "Houndour", types: ["Dark", "Fire"] },
  { dexNumber: 229, name: "Houndoom", types: ["Dark", "Fire"] },
  { dexNumber: 230, name: "Kingdra", types: ["Water", "Dragon"] },
  { dexNumber: 231, name: "Phanpy", types: ["Ground"] },
  { dexNumber: 232, name: "Donphan", types: ["Ground"] },
  { dexNumber: 233, name: "Porygon2", types: ["Normal"] },
  { dexNumber: 234, name: "Stantler", types: ["Normal"] },
  { dexNumber: 235, name: "Smeargle", types: ["Normal"] },
  { dexNumber: 236, name: "Tyrogue", types: ["Fighting"] },
  { dexNumber: 237, name: "Hitmontop", types: ["Fighting"] },
  { dexNumber: 238, name: "Smoochum", types: ["Ice", "Psychic"] },
  { dexNumber: 239, name: "Elekid", types: ["Electric"] },
  { dexNumber: 240, name: "Magby", types: ["Fire"] },
  { dexNumber: 241, name: "Miltank", types: ["Normal"] },
  { dexNumber: 242, name: "Blissey", types: ["Normal"] },
  { dexNumber: 243, name: "Raikou", types: ["Electric"] },
  { dexNumber: 244, name: "Entei", types: ["Fire"] },
  { dexNumber: 245, name: "Suicune", types: ["Water"] },
  { dexNumber: 246, name: "Larvitar", types: ["Rock", "Ground"] },
  { dexNumber: 247, name: "Pupitar", types: ["Rock", "Ground"] },
  { dexNumber: 248, name: "Tyranitar", types: ["Rock", "Dark"] },
  { dexNumber: 249, name: "Lugia", types: ["Psychic", "Flying"] },
  { dexNumber: 250, name: "Ho-Oh", types: ["Fire", "Flying"] },
  { dexNumber: 251, name: "Celebi", types: ["Psychic", "Grass"] },

  // Gen 3 (252-386)
  { dexNumber: 252, name: "Treecko", types: ["Grass"] },
  { dexNumber: 253, name: "Grovyle", types: ["Grass"] },
  { dexNumber: 254, name: "Sceptile", types: ["Grass"] },
  { dexNumber: 255, name: "Torchic", types: ["Fire"] },
  { dexNumber: 256, name: "Combusken", types: ["Fire", "Fighting"] },
  { dexNumber: 257, name: "Blaziken", types: ["Fire", "Fighting"] },
  { dexNumber: 258, name: "Mudkip", types: ["Water"] },
  { dexNumber: 259, name: "Marshtomp", types: ["Water", "Ground"] },
  { dexNumber: 260, name: "Swampert", types: ["Water", "Ground"] },
  { dexNumber: 261, name: "Poochyena", types: ["Dark"] },
  { dexNumber: 262, name: "Mightyena", types: ["Dark"] },
  { dexNumber: 263, name: "Zigzagoon", types: ["Normal"] },
  { dexNumber: 264, name: "Linoone", types: ["Normal"] },
  { dexNumber: 265, name: "Wurmple", types: ["Bug"] },
  { dexNumber: 266, name: "Silcoon", types: ["Bug"] },
  { dexNumber: 267, name: "Beautifly", types: ["Bug", "Flying"] },
  { dexNumber: 268, name: "Cascoon", types: ["Bug"] },
  { dexNumber: 269, name: "Dustox", types: ["Bug", "Poison"] },
  { dexNumber: 270, name: "Lotad", types: ["Water", "Grass"] },
  { dexNumber: 271, name: "Lombre", types: ["Water", "Grass"] },
  { dexNumber: 272, name: "Ludicolo", types: ["Water", "Grass"] },
  { dexNumber: 273, name: "Seedot", types: ["Grass"] },
  { dexNumber: 274, name: "Nuzleaf", types: ["Grass", "Dark"] },
  { dexNumber: 275, name: "Shiftry", types: ["Grass", "Dark"] },
  { dexNumber: 276, name: "Taillow", types: ["Normal", "Flying"] },
  { dexNumber: 277, name: "Swellow", types: ["Normal", "Flying"] },
  { dexNumber: 278, name: "Wingull", types: ["Water", "Flying"] },
  { dexNumber: 279, name: "Pelipper", types: ["Water", "Flying"] },
  { dexNumber: 280, name: "Ralts", types: ["Psychic", "Fairy"] },
  { dexNumber: 281, name: "Kirlia", types: ["Psychic", "Fairy"] },
  { dexNumber: 282, name: "Gardevoir", types: ["Psychic", "Fairy"] },
  { dexNumber: 283, name: "Surskit", types: ["Bug", "Water"] },
  { dexNumber: 284, name: "Masquerain", types: ["Bug", "Flying"] },
  { dexNumber: 285, name: "Shroomish", types: ["Grass"] },
  { dexNumber: 286, name: "Breloom", types: ["Grass", "Fighting"] },
  { dexNumber: 287, name: "Slakoth", types: ["Normal"] },
  { dexNumber: 288, name: "Vigoroth", types: ["Normal"] },
  { dexNumber: 289, name: "Slaking", types: ["Normal"] },
  { dexNumber: 290, name: "Nincada", types: ["Bug", "Ground"] },
  { dexNumber: 291, name: "Ninjask", types: ["Bug", "Flying"] },
  { dexNumber: 292, name: "Shedinja", types: ["Bug", "Ghost"] },
  { dexNumber: 293, name: "Whismur", types: ["Normal"] },
  { dexNumber: 294, name: "Loudred", types: ["Normal"] },
  { dexNumber: 295, name: "Exploud", types: ["Normal"] },
  { dexNumber: 296, name: "Makuhita", types: ["Fighting"] },
  { dexNumber: 297, name: "Hariyama", types: ["Fighting"] },
  { dexNumber: 298, name: "Azurill", types: ["Normal", "Fairy"] },
  { dexNumber: 299, name: "Nosepass", types: ["Rock"] },
  { dexNumber: 300, name: "Skitty", types: ["Normal"] },
  { dexNumber: 301, name: "Delcatty", types: ["Normal"] },
  { dexNumber: 302, name: "Sableye", types: ["Dark", "Ghost"] },
  { dexNumber: 303, name: "Mawile", types: ["Steel", "Fairy"] },
  { dexNumber: 304, name: "Aron", types: ["Steel", "Rock"] },
  { dexNumber: 305, name: "Lairon", types: ["Steel", "Rock"] },
  { dexNumber: 306, name: "Aggron", types: ["Steel", "Rock"] },
  { dexNumber: 307, name: "Meditite", types: ["Fighting", "Psychic"] },
  { dexNumber: 308, name: "Medicham", types: ["Fighting", "Psychic"] },
  { dexNumber: 309, name: "Electrike", types: ["Electric"] },
  { dexNumber: 310, name: "Manectric", types: ["Electric"] },
  { dexNumber: 311, name: "Plusle", types: ["Electric"] },
  { dexNumber: 312, name: "Minun", types: ["Electric"] },
  { dexNumber: 313, name: "Volbeat", types: ["Bug"] },
  { dexNumber: 314, name: "Illumise", types: ["Bug"] },
  { dexNumber: 315, name: "Roselia", types: ["Grass", "Poison"] },
  { dexNumber: 316, name: "Gulpin", types: ["Poison"] },
  { dexNumber: 317, name: "Swalot", types: ["Poison"] },
  { dexNumber: 318, name: "Carvanha", types: ["Water", "Dark"] },
  { dexNumber: 319, name: "Sharpedo", types: ["Water", "Dark"] },
  { dexNumber: 320, name: "Wailmer", types: ["Water"] },
  { dexNumber: 321, name: "Wailord", types: ["Water"] },
  { dexNumber: 322, name: "Numel", types: ["Fire", "Ground"] },
  { dexNumber: 323, name: "Camerupt", types: ["Fire", "Ground"] },
  { dexNumber: 324, name: "Torkoal", types: ["Fire"] },
  { dexNumber: 325, name: "Spoink", types: ["Psychic"] },
  { dexNumber: 326, name: "Grumpig", types: ["Psychic"] },
  { dexNumber: 327, name: "Spinda", types: ["Normal"] },
  { dexNumber: 328, name: "Trapinch", types: ["Ground"] },
  { dexNumber: 329, name: "Vibrava", types: ["Ground", "Dragon"] },
  { dexNumber: 330, name: "Flygon", types: ["Ground", "Dragon"] },
  { dexNumber: 331, name: "Cacnea", types: ["Grass"] },
  { dexNumber: 332, name: "Cacturne", types: ["Grass", "Dark"] },
  { dexNumber: 333, name: "Swablu", types: ["Normal", "Flying"] },
  { dexNumber: 334, name: "Altaria", types: ["Dragon", "Flying"] },
  { dexNumber: 335, name: "Zangoose", types: ["Normal"] },
  { dexNumber: 336, name: "Seviper", types: ["Poison"] },
  { dexNumber: 337, name: "Lunatone", types: ["Rock", "Psychic"] },
  { dexNumber: 338, name: "Solrock", types: ["Rock", "Psychic"] },
  { dexNumber: 339, name: "Barboach", types: ["Water", "Ground"] },
  { dexNumber: 340, name: "Whiscash", types: ["Water", "Ground"] },
  { dexNumber: 341, name: "Corphish", types: ["Water"] },
  { dexNumber: 342, name: "Crawdaunt", types: ["Water", "Dark"] },
  { dexNumber: 343, name: "Baltoy", types: ["Ground", "Psychic"] },
  { dexNumber: 344, name: "Claydol", types: ["Ground", "Psychic"] },
  { dexNumber: 345, name: "Lileep", types: ["Rock", "Grass"] },
  { dexNumber: 346, name: "Cradily", types: ["Rock", "Grass"] },
  { dexNumber: 347, name: "Anorith", types: ["Rock", "Bug"] },
  { dexNumber: 348, name: "Armaldo", types: ["Rock", "Bug"] },
  { dexNumber: 349, name: "Feebas", types: ["Water"] },
  { dexNumber: 350, name: "Milotic", types: ["Water"] },
  { dexNumber: 351, name: "Castform", types: ["Normal"] },
  { dexNumber: 352, name: "Kecleon", types: ["Normal"] },
  { dexNumber: 353, name: "Shuppet", types: ["Ghost"] },
  { dexNumber: 354, name: "Banette", types: ["Ghost"] },
  { dexNumber: 355, name: "Duskull", types: ["Ghost"] },
  { dexNumber: 356, name: "Dusclops", types: ["Ghost"] },
  { dexNumber: 357, name: "Tropius", types: ["Grass", "Flying"] },
  { dexNumber: 358, name: "Chimecho", types: ["Psychic"] },
  { dexNumber: 359, name: "Absol", types: ["Dark"] },
  { dexNumber: 360, name: "Wynaut", types: ["Psychic"] },
  { dexNumber: 361, name: "Snorunt", types: ["Ice"] },
  { dexNumber: 362, name: "Glalie", types: ["Ice"] },
  { dexNumber: 363, name: "Spheal", types: ["Ice", "Water"] },
  { dexNumber: 364, name: "Sealeo", types: ["Ice", "Water"] },
  { dexNumber: 365, name: "Walrein", types: ["Ice", "Water"] },
  { dexNumber: 366, name: "Clamperl", types: ["Water"] },
  { dexNumber: 367, name: "Huntail", types: ["Water"] },
  { dexNumber: 368, name: "Gorebyss", types: ["Water"] },
  { dexNumber: 369, name: "Relicanth", types: ["Water", "Rock"] },
  { dexNumber: 370, name: "Luvdisc", types: ["Water"] },
  { dexNumber: 371, name: "Bagon", types: ["Dragon"] },
  { dexNumber: 372, name: "Shelgon", types: ["Dragon"] },
  { dexNumber: 373, name: "Salamence", types: ["Dragon", "Flying"] },
  { dexNumber: 374, name: "Beldum", types: ["Steel", "Psychic"] },
  { dexNumber: 375, name: "Metang", types: ["Steel", "Psychic"] },
  { dexNumber: 376, name: "Metagross", types: ["Steel", "Psychic"] },
  { dexNumber: 377, name: "Regirock", types: ["Rock"] },
  { dexNumber: 378, name: "Regice", types: ["Ice"] },
  { dexNumber: 379, name: "Registeel", types: ["Steel"] },
  { dexNumber: 380, name: "Latias", types: ["Dragon", "Psychic"] },
  { dexNumber: 381, name: "Latios", types: ["Dragon", "Psychic"] },
  { dexNumber: 382, name: "Kyogre", types: ["Water"] },
  { dexNumber: 383, name: "Groudon", types: ["Ground"] },
  { dexNumber: 384, name: "Rayquaza", types: ["Dragon", "Flying"] },
  { dexNumber: 385, name: "Jirachi", types: ["Steel", "Psychic"] },
  { dexNumber: 386, name: "Deoxys", types: ["Psychic"] }
];